baseURL: 'https://gilgames-livros.netlify.app/'
title: GILGAMEŜ livros
paginate: 5
theme: PaperModX
# NOTE remove this line if you copy exampleSite out of hugo-PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  description: 'Theme PaperModX - https://github.com/reorx/hugo-PaperModX'
  author:
    - Reorx
  mainSections:
    - docs
    - posts
  disableAnchoredHeadings: true
  images: ['cover.png']
  DateFormat: '2006-01-02'
  # Defini como false pois criou problemas no deploy. Depois devo mudar para ter acesso ao SEO, mas tenho de preencher o custom_analytics.html com o Tracking_ID
  useCustomAnalytics: false

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  ShowWordCount: false
  # disableSpecial1stPost: true
  displayFullLangName: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  EnableInstantClick: true
  EnableImageZoom: true

  commentSystems:
    disqus:
      shortname: reorx
    remark42:
      url: https://remark42.reorx.com
      site: reorx.github.io
    telegramWidget:
      channel: reorx_share
      accentColor: '9077e1'
      limit: 20
  defaultCommentSystems:
    remark42: false

  profileMode:
    enabled: false
    title: PaperModX
    imageUrl: '#'
    imageTitle: my image
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Archives
        url: /archives/
      - name: Tags
        url: /tags/
      - name: Categories
        url: /categories/
      - name: Docs
        url: /docs/
      - name: Artigo
        url: /artigo/

  homeInfoParams:
    Title: 'Bem-vindos à GILGAMEŜ livros'
    Content: |
      Somos um projecto alfarrabista que se dedica à venda de livros usados e novos. O nosso objectivo é promover a leitura e a cultura, disponibilizando livros a preços acessíveis. Visite o nosso Instagram @gilgames_livros.

    Image: /image/gilgamesh.webp

  socialIcons:
    - name: instagram
      url: 'https://www.instagram.com/gilgames_livros/'

  editPost:
    URL: 'https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content'
    Text: 'Suggest Changes' # edit text
    appendFilePath: true # to append file path to Edit link

  label:
    text: 'Home'
    icon: icon.png
    iconHeight: 35

  assets:
    disableHLJS: true
    favicon: 'assets/favicon.ico'
    favicon16x16: 'assets/favicon-16x16.png'
    favicon32x32: 'assets/favicon-32x32.png'
    apple_touch_icon: 'assets/apple-touch-icon.png'
    safari_pinned_tab: '<link / abs url>'

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: 'Português'
    weight: 1
    menu:
      main:
        # Remoção da Newsletter e Docs do site
        # - name: Newsletter
        #   url: /newsletter/
        #   weight: 1
        - name: Tags
          url: /tags/
          weight: 4
        - name: Categorias
          url: /categories/
          weight: 5
        - name: Arquivo
          url: /archives/
          weight: 6
        # - name: Pesquisa
        #   url: /search/
        #   weight: 10
        - name: 'Instagram'
          url: 'https://www.instagram.com/gilgames_livros/'
          params:
            external: true
